film/urls.py
from django.urls import path
from film.views import IndexView, FilmsView, FilmView, FilmLoginView, RegistrationView, SettingsView, ProfileView, \
    FilmLogoutView, AddToFavorites

urlpatterns = [
    path(r'', IndexView.as_view(), name='index'),
    path(r'films', FilmsView.as_view(), name='films'),
    path(r'film/<slug>', FilmView.as_view(), name='film'),
    path(r'film/add_to_fav/<slug>', AddToFavorites.as_view(), name='fav'),
    path(r'login', FilmLoginView.as_view(), name='login'),
    path(r'logout', FilmLogoutView.as_view(), name='logout'),
    path(r'registration', RegistrationView.as_view(), name='registration'),
    path(r'profile', ProfileView.as_view(), name='profile'),
    path(r'settings', SettingsView.as_view(), name='settings'),
]

watch_rate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from watch_rate import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('film.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

film/models.py
from django.core import validators
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.datetime_safe import datetime
from django.utils.translation import gettext_lazy as _


def is_valid_year(val):
    if not 1800 < val < datetime.today().year + 10:
        raise validators.ValidationError('Year should be real')


def is_valid_age(val):
    if not 0 <= val <= 21:
        raise validators.ValidationError('Year should be real')


class User(AbstractUser):
    avatar = models.ImageField(blank=True, upload_to='img', verbose_name='Аватар')
    email = models.EmailField(blank=False, unique=True, verbose_name='Почта')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Film(models.Model):
    name = models.TextField(verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Слаг')
    producer = models.ManyToManyField(to='Person', related_name='m2m_producers', verbose_name='Продюсер')
    year = models.IntegerField(validators=[is_valid_year], verbose_name='Год')
    country = models.ManyToManyField(to='Country', verbose_name='Страна')
    genre = models.ManyToManyField(to='Genre', verbose_name='Жанр')
    actors = models.ManyToManyField(to='Person', related_name='m2m_actors', verbose_name='Актеры')
    age = models.IntegerField(blank=True, null=True, validators=[is_valid_age], verbose_name='Возраст')
    time = models.CharField(max_length=16, verbose_name='Время')
    user_rating = models.IntegerField(blank=True, default=1, verbose_name='Рейтинг')
    plot = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class FavoriteFilms(models.Model):
    uID = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Айди пользователя')
    fID = models.ForeignKey(to=Film, on_delete=models.CASCADE, verbose_name='Айди фильма')

    class Meta:
        unique_together = ('uID', 'fID')
        verbose_name = 'Избранный фильм'
        verbose_name_plural = 'Избранные фильмы'


class Person(models.Model):
    first_name = models.TextField(verbose_name='Имя')
    last_name = models.TextField(verbose_name='Фамилия')
    role = models.ManyToManyField(to='Role', verbose_name='Роль')

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Персона'
        verbose_name_plural = 'Персоны'


class Role(models.Model):
    name = models.TextField(verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'


class Genre(models.Model):
    name = models.TextField(verbose_name='Название')
    about = models.TextField(verbose_name='О')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Country(models.Model):
    name = models.TextField(verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Vote(models.Model):
    mark = models.IntegerField(validators=[validators.MinValueValidator(1), validators.MaxValueValidator(10)], verbose_name='Оценка')
    film = models.ForeignKey(to='Film', on_delete=models.CASCADE, verbose_name='Название')

    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

film/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm, UserChangeForm
from django import forms
from django.utils.text import slugify
from . import models


class LoginForm(AuthenticationForm):
    username = UsernameField(
        label='Login',
        min_length=4,
        max_length=15,
        widget=forms.TextInput(attrs={
            'autofocus': 'true', 'class': 'form-control',
            'placeholder': 'login',
            'id': 'login-pass',
        }),
    )
    password = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password',
            'id': 'login-pass',
        }),
    )


class CreateAccount(UserCreationForm):
    username = forms.CharField(
        label='Login',
        min_length=4,
        max_length=15,
        widget=forms.TextInput(attrs={
            'autofocus': 'true',
            'class': 'form-control',
            'placeholder': 'login',
            'id': 'login-pass',
        }),
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'e-mail',
            'id': 'login-pass',
        }),
    )
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password',
            'id': 'login-pass',
        }),
    )
    password2 = forms.CharField(
        label='Repeat password',
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'repeat password',
            'id': 'login-pass',
        }),
    )

    class Meta:
        model = models.User
        fields = ['username', 'email', 'avatar', ]
        widgets = {
            'avatar': forms.FileInput(attrs={
                'type': 'file',
                'class': 'choose-avatar',
                'id': 'Avatar',
            }),
        }


class SettingsForm(forms.ModelForm):
    username = forms.CharField(
        label='Login',
        min_length=4,
        max_length=15,
        widget=forms.TextInput(attrs={
            'autofocus': 'true',
            'class': 'form-control',
            'placeholder': 'login',
            'id': 'login-pass',
        }),
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'autofocus': 'true', 'class': 'form-control',
            'placeholder': 'e-mail',
            'id': 'login-pass',
        })
    )
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'password',
            'id': 'login-pass',
        }),
        required=False
    )
    password2 = forms.CharField(
        label='Repeat password',
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'repeat password',
            'id': 'login-pass',
        }),
        required=False
    )

    def is_valid(self):
        return super().is_valid() and self.cleaned_data.get('password1') == self.cleaned_data.get('password2')

    class Meta:
        model = models.User
        fields = ['username', 'email', 'avatar', ]
        widgets = {
            'avatar': forms.FileInput(attrs={
                'type': 'file',
                'class': 'choose-avatar',
                'id': 'Avatar',
            }),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        new_pass = self.cleaned_data.get('password1')
        if new_pass != '':
            user.set_password(new_pass)
        if commit:
            user.save()
        return user


class AddFilmForm(forms.ModelForm):
    name = forms.CharField(
        label='Name',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'required-field'}),
    ),

    producer = forms.ModelMultipleChoiceField(
        label='Producer',
        queryset=models.Person.objects.filter(role__name='Producer').all(),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-control',
        }),
        required=False,
    )
    country = forms.ModelMultipleChoiceField(
        label='Country',
        queryset=models.Country.objects.all(),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-control',
        }),
        required=False,
    )
    genre = forms.ModelMultipleChoiceField(
        label='Genre',
        queryset=models.Genre.objects.all(),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-control',
        }),
        required=False,
    )
    actors = forms.ModelMultipleChoiceField(
        label='Actors',
        queryset=models.Person.objects.filter(role__name='Актер').all(),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-control',
        }),
        required=False,
    )

    def save(self, commit=True):
        film = super().save(commit)
        if commit:
            film.slug = slugify(str(film.pk) + "-" + film.name)
            film.save()
        return film

    class Meta:
        model = models.Film
        fields = ['name', 'producer', 'year', 'country', 'genre', 'actors', 'age', 'time', 'plot', 'image', ]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'year': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'country': forms.TextInput(attrs={
                'class': 'form-control',
             }),
            'genre': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'actors': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'age': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'plot': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'image': forms.FileInput(attrs={
                'type': 'file',
                'class': 'choose-avatar',
                'id': 'image_film',
            }),
        }

film/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import UpdateView, FormMixin
from film import forms
from film.forms import LoginForm, CreateAccount, SettingsForm
from film.models import Film, User, FavoriteFilms


class IndexView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('films'))
        return super(IndexView, self).get(request, *args, **kwargs)


class FilmsView(LoginRequiredMixin, ListView, FormMixin):
    login_url = reverse_lazy('login')
    model = Film
    paginate_by = 10
    template_name = 'films.html'
    queryset = model.objects.order_by('name')
    form_class = forms.AddFilmForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.AddFilmForm
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            new_film = form.save(commit=True)
            return JsonResponse({
                'href': reverse('film', kwargs={'slug': new_film.slug}),
            })
        return JsonResponse({
            'errors': form.errors,
        }, status=400)


class FilmView(LoginRequiredMixin, DetailView):
    template_name = 'film.html'
    login_url = reverse_lazy('login')
    model = Film

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        film = Film.objects.get(slug=self.kwargs['slug'])
        context['fav'] = FavoriteFilms.objects.filter(uID=self.request.user, fID=film)
        context['user_list'] = FavoriteFilms.objects.filter(fID=film)
        return context


class AddToFavorites(LoginRequiredMixin, View):
    login_url = reverse_lazy('login')

    def post(self, request, slug, *args, **kwargs):
        try:
            FavoriteFilms.objects.get(uID=request.user, fID__slug=slug).delete()
        except FavoriteFilms.DoesNotExist:
            film = Film.objects.get(slug=slug)
            FavoriteFilms.objects.create(uID=request.user, fID=film)

        return HttpResponse(status=200)


class FilmLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = LoginForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse('films')


class FilmLogoutView(LogoutView):
    def get_next_page(self):
        return reverse('index')


class RegistrationView(CreateView):
    template_name = 'registration.html'
    form_class = CreateAccount

    def get_success_url(self):
        return reverse('profile')


class SettingsView(UpdateView):
    template_name = 'settings.html'
    form_class = SettingsForm
    success_url = 'profile'
    model = User

    def get_object(self, queryset=None):
        return self.request.user


class ProfileView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['films'] = Film.objects.filter(favoritefilms__uID=self.request.user)
        return context

film/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="shotcut icon" type="image/x-icon" href="{% static "img/camera.ico" %}">
  <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap-4.1.3-dist/css/bootstrap.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "css/film.css" %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body class="site-color">
<header>
  <nav class="navbar navbar-color navbar-expand-lg navbar-light">
    <a class="navbar-brand head-site" href="{% url 'index' %}">Watch&rate</a>
    <button class="navbar-toggler search-but-style" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {#      <form class="form-inline navnar-search mt-2 mt-md-0">#}
        {#        <input class="form-control search-field mr-sm-2" id="search-input" placeholder="Search" aria-label="Search">#}
        {#        <button class="search-but-style my-sm-0 search-but-text" type="submit">Find</button>#}
        {#      </form>#}
        <li class="nav-item">
          <div class="nav-link">

            <a class="but but-pretty" href="{% url 'films' %}">Catalog</a>
          </div>
        </li>
      </ul>

      {% if request.user.is_authenticated %}
        <div class="usr">
          {% if request.user.avatar %}
            <img src="{% get_media_prefix %}{{ request.user.avatar }}" class="avatar">
          {% else %}
            <img src="{% static "img/ketnipz.png" %}" class="avatar">
          {% endif %}
        <div class="usr-text-block">
          <div class="usr-row">
            <a href="{% url 'profile' %}" class="usr-item user-name">{{ request.user.username }}</a>
          </div>
          <div class="usr-row">
            <a href="{% url 'settings' %}" class="usr-item user-item">Settings</a>
            <a href="{% url 'logout' %}" class="user-item user-item">Log out</a>
          </div>
        </div>
      {% endif %}
      </div>
    </div>
  </nav>
</header>

<div class="main ml-5 mr-5">
  <div class="row justify-content-center">
    {% block content %}
    {% endblock content %}
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="{% static "/vendor/bootstrap-4.1.3-dist/js/bootstrap.min.js" %}"></script>
{% block extra_scripts %}
{% endblock extra_scripts %}
</body>
</html>

film/templates/cardfilm.html
{% load static %}

  <div class="card catalog-elem film-card">
    {% if film.image %}
      <img class="cat-ava-film" id="image_film" src="{% get_media_prefix %}{{ film.image }}" alt="">
    {% else %}
      <img class="cat-ava-film" id="image_film" src="{% static "img/no_picture.png" %}" alt="">
    {% endif %}
    <div class="card-body">
      <h5 class="card-title name-film">{{ film.name }}</h5>
      <p class="card-text cat-plot">{{ film.plot | truncatewords:20}}</p>
      <a href="{% url 'film' film.slug %}" class="but but-pretty">Read more</a>
    </div>
  </div>

film/templates/film.html
{% extends "base.html" %}
{% load static %}
{% block title %}Watch&rate: film {{ film.name }}{% endblock title %}

{% block content %}
  <div class="col-lg-6 col-md-8">
    <div class="header-film row">
      <h4 class="p-0 m-0 name-film">{{ film.name }}</h4>
    </div>
    <div class="row">
      <div class="functional">
        {% if film.image %}
          <img class="img-fluid film-avatar" id="image_film" src="{% get_media_prefix %}{{ film.image }}" alt="">
        {% else %}
          <img class="img-fluid film-avatar" id="image_film" src="{% static "img/no_picture.png" %}" alt="">
        {% endif %}
        <div class="rate-film-block">
          {% csrf_token %}
          {% if fav %}
            <button class="but but-pretty delete-button" id="add_to_fav">Remove from favorites</button>
          {% else %}
            <button class="but but-pretty" id="add_to_fav">Add to favorites</button>
          {% endif %}
        </div>
        <div class="rate-film-block">
          <button class="but" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false"
                  aria-controls="collapseExample">Who added it too?
          </button>
        </div>
        <div class="collapse" id="collapseExample">
          {% for user in user_list %}
            <ul class="who-added">
              <li class="who-added-content">
{#                <p class="who-added-content">#}
                  {{ user.uID.username }}
{#                </p>#}
              </li>
            </ul>
          {% empty %}
            <h1 class="error-users">There are no users who have added this movie to themselves, but you can be the first</h1>
          {% endfor %}
        </div>
      </div>

      <div class="table-film-block">
        <table class="table-film">
          <tbody>
          <tr>
            <td class="info-film-left">Year</td>
            <td class="info-film-right">{{ film.year }}</td>
          </tr>

          <tr>
            <td class="info-film-left">Country</td>
            <td class="info-film-right">
              {% for c in film.country.all %}
                {{ c.name }}
              {% endfor %}
            </td>
          </tr>

          <tr>
            <td class="info-film-left">Producer</td>
            <td class="info-film-right">
              {% for p in film.producer.all %}
                {{ p.first_name }}{{ p.last_name }}
              {% endfor %}
            </td>
          </tr>

          <tr>
            <td class="info-film-left">Genre</td>
            <td class="info-film-right">
              {% for g in film.genre.all %}
                {{ g.name }}
              {% endfor %}
            </td>
          </tr>

          <tr>
            <td class="info-film-left">Age</td>
            <td class="info-film-right">{{ film.age }}</td>
          </tr>

          <tr>
            <td class="info-film-left">Time</td>
            <td class="info-film-right">{{ film.time }}</td>
          </tr>

          <tr>
            <td class="info-film-left">Plot</td>
            <td class="info-film-right">{{ film.plot }}</td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

{% block extra_scripts %}
  <script src="{% static "js/add_to_fav.js" %}"></script>
{% endblock extra_scripts %}

film/templates/films.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Watch&rate: catalog{% endblock title %}

{% block content %}
  <div class="col-lg-6 col-md-8">
    <div class="header-film row">
      <h4 class="p-0 m-0 name-film">Catalog</h4>
      <!-- Button trigger modal -->
      <button type="button" class="but but-pretty" data-toggle="modal" data-target="#addfilm">
        Add film
      </button>
      <!-- Modal -->
      <div class="modal fade" id="addfilm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
           aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="name-film modal-title" id="exampleModalLabel">Add film</h5>
              <button type="button" class="close but" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form class="film_form" action="{% url 'films' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if next %}
                  <strong>
                    <div class="errors">Please check your data</div>
                  </strong>
                {% endif %}
                {% if form.errors %}
                  {% for error in form.non_field_errors %}
                    <div class="errors">
                      <strong>{{ error|escape }}</strong>
                    </div>
                  {% endfor %}
                {% endif %}
                {% for field in form %}
                  <div class="form-group row">
                    <label for="{{ field.id_for_label }}"
                           class="col-sm-3 col-form-label film_form">{{ field.label }}</label>
                    {% for error in field.errors %}
                      <div class="errors">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                    <div class="col-sm-9"> {{ field.as_widget }} </div>
                  </div>
                {% endfor %}
                <input type="hidden" name="next" value="{{ next }}"/>
                <div class="col-sm-7 form-group row">
                  <div class="modal-footer">
                    <button type="button" class="but but-pretty" data-dismiss="modal">Close</button>
                    <button id="save_changes" type="submit" class="but but-pretty">Save changes</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row catalog">
      {% for film in film_list %}
        {% include 'cardfilm.html' %}
      {% empty %}
        <h1 class="errors">There are no films in the catalog yet, but you can add them</h1>
      {% endfor %}
    </div>
    {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="page-list pagination">
          {% if page_obj.has_previous %}
            <li class="page-list__item">
              <a class="page-list__page1" href="{% url 'films' %}?page={{ page_obj.previous_page_number }}"
                 aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            <li class="page-list__item"><a class="page-list__page" href="{% url 'films' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            </li>
          {% endif %}
          <li class="page-list__item"><a class="page-list__page active" href="#">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
            <li class="page-list__item"><a class="page-list__page" href="{% url 'films' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            </li>
            <li class="page-list__item">
              <a class="page-list__page1" href="{% url 'films' %}?page={{ page_obj.next_page_number }}"
                 aria-label="Next">
                <span aria-hidden="true">&raquo</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock content %}

{% block extra_scripts %}
  <script src="{% static "js/film.js" %}"></script>
{% endblock extra_scripts %}

film/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Watch&rate{% endblock title %}

{% block content %}
  <div class="col-lg-6 col-md-8">
    <h1 class="intro-site link-watch-rate" href="">Watch & rate</h1>
    <div>
      <h2 class="text-header">
        <a class="but but-pretty" href="{% url 'login' %}">sign in</a> or
        <a class="but but-pretty" href="{% url 'registration' %}">sign up</a>
        <br>to see the catalog, find out information about the films, add them to favorites category or like it!
      </h2>
    </div>
  </div>
{% endblock content %}

film/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Watch&rate: login{% endblock title %}

{% block content %}
  <div class="col-lg-6 col-md-8">
    <div class="header-film row">
      <h4 class="p-0 m-0 name-film">Log In</h4>
    </div>

    <div class="header-film row">
      <form class="login" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% if next %}
          <strong>
            <div class="errors">Please login to see the {{ next }} </div>
          </strong>
        {% endif %}
        {% if form.errors %}
          {% for error in form.non_field_errors %}
            <div class="errors">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endif %}
        {% for field in form %}
          <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label login">{{ field.label }}</label>
            {% for error in field.errors %}
              <div class="errors">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
            <div class="col-sm-5">{{ field.as_widget }}</div>
          </div>
        {% endfor %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-group row">
          <button class="but but-pretty" type="submit">Sign in</button>
          <a class="but" href="{% url 'registration' %}">Create new account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

film/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Watch&rate: profile{% endblock title %}

{% block content %}
  <div class="col-lg-6 col-md-8">
    <div class="header-film row">
      <h4 class="p-0 m-0 name-film">Profile</h4>
    </div>
    <div class="header-film row">
      <form class="login">
        <div class="form-group row">
          <label for="staticLogin" class="col-sm-4 col-form-label login">Login</label>
          <div class="col-sm-8">
            <input type="text" required readonly class="form-control" id="staticLogin" value="{{ user.username }}">
          </div>
        </div>

        <div class="form-group row">
          <label for="email" class="col-sm-4 col-form-label login">E-mail</label>
          <div class="col-sm-8">
            <input type="text" required readonly class="form-control" id="email" value="{{ user.email }}">
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-4 col-form-label login">Avatar</label>
          <div class="col-sm-5">
            {% if request.user.avatar %}
              <img src="{% get_media_prefix %}{{ request.user.avatar }}" class="avatar">
            {% else %}
              <img src="{% static "img/ketnipz.png" %}" class="avatar">
            {% endif %}
          </div>
        </div>
        <div class="p-0 m-0 form-group row">
          <a class="but but-pretty" href="{% url 'settings' %}">Settings</a>
        </div>
      </form>
    </div>
    <div class="line-separator"></div>

    <h4 class="p-0 m-0 name-film">Favorites</h4>
    <div class="header-film row">
      {% for film in films %}
        {% include 'cardfilm.html' %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}